export interface WalletIcon {
  id: number;
  slug: string;
  name: string;
  nameLocal?: string;
  type: 'bank' | 'wallet';
  subtype?: string;
  country: string;
  region?: string;
  currency?: string;
  domain: string;
  logoClearbit?: string;
  logoBrandfetch?: string;
  logoSvgl?: string;
  brandColor?: string;
  swiftBic?: string;
  notes?: string;
}

export const COUNTRY_NAMES_ZH: Record<string, string> = {
  'China': '中国',
  'United States': '美国',
  'United Kingdom': '英国',
  'Singapore': '新加坡',
  'Malaysia': '马来西亚',
  'India': '印度',
  'Japan': '日本',
  'South Korea': '韩国',
  'Canada': '加拿大',
  'Australia': '澳大利亚',
  'Germany': '德国',
  'France': '法国',
  'Switzerland': '瑞士',
  'Netherlands': '荷兰',
  'Spain': '西班牙',
  'Italy': '意大利',
  'Sweden': '瑞典',
  'Denmark': '丹麦',
  'Brazil': '巴西',
  'Argentina': '阿根廷',
  'Philippines': '菲律宾',
  'Indonesia': '印度尼西亚',
  'Thailand': '泰国',
  'Vietnam': '越南',
  'Kenya': '肯尼亚',
  'Global': '全球',
};

export const WALLET_ICONS: WalletIcon[] = [
  { id: 1, slug: 'ICBC', name: 'Industrial and Commercial Bank of China', nameLocal: '中国工商银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'icbc.com.cn', logoClearbit: 'https://logo.clearbit.com/icbc.com.cn', logoBrandfetch: 'https://cdn.brandfetch.io/icbc.com.cn/w/200/h/200', brandColor: '#C6000C', swiftBic: 'ICBKCNBJ', notes: 'Big Four' },
  { id: 2, slug: 'ABC', name: 'Agricultural Bank of China', nameLocal: '中国农业银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'abchina.com', logoClearbit: 'https://logo.clearbit.com/abchina.com', logoBrandfetch: 'https://cdn.brandfetch.io/abchina.com/w/200/h/200', logoSvgl: 'https://pic.616pic.com/ys_bnew_img/00/06/23/7IUxX6TJoQ.jpg', brandColor: '#007B40', swiftBic: 'ABOCCNBJ', notes: 'Big Four' },
  { id: 3, slug: 'BOC', name: 'Bank of China', nameLocal: '中国银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'boc.cn', logoClearbit: 'https://logo.clearbit.com/boc.cn', logoBrandfetch: 'https://cdn.brandfetch.io/boc.cn/w/200/h/200', logoSvgl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLYP2jixNNBrVOZoDctCVWMJlOa7grGxWVcQ&s', brandColor: '#C8161D', swiftBic: 'BKCHCNBJ', notes: 'Big Four' },
  { id: 4, slug: 'CCB', name: 'China Construction Bank', nameLocal: '中国建设银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'ccb.com', logoClearbit: 'https://logo.clearbit.com/ccb.com', logoBrandfetch: 'https://cdn.brandfetch.io/ccb.com/w/200/h/200', logoSvgl: 'https://play-lh.googleusercontent.com/gdoOhSSTCRXJ330CxaNbBj7EVRKsVqNjTlT_-__1O9e0uGjAZFTS5Dk0sn4t2gbbAEWI', brandColor: '#005BAC', swiftBic: 'PCBCCNBJ', notes: 'Big Four' },
  { id: 5, slug: 'BoCom', name: 'Bank of Communications', nameLocal: '交通银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'bankcomm.com', logoClearbit: 'https://logo.clearbit.com/bankcomm.com', logoBrandfetch: 'https://cdn.brandfetch.io/bankcomm.com/w/200/h/200', brandColor: '#006DB7', swiftBic: 'COMMCNSH', notes: 'Big Five' },
  { id: 6, slug: 'CMB', name: 'China Merchants Bank', nameLocal: '招商银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'cmbchina.com', logoClearbit: 'https://logo.clearbit.com/cmbchina.com', logoBrandfetch: 'https://cdn.brandfetch.io/cmbchina.com/w/200/h/200', logoSvgl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQfA5mRTnwgSCrUIqs6XhKvPP4xvSirc53cg&s', brandColor: '#C8161D', swiftBic: 'CMBCCNBS', notes: 'National Joint-Stock' },
  { id: 7, slug: 'CITIC', name: 'China CITIC Bank', nameLocal: '中信银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'citicbank.com', logoClearbit: 'https://logo.clearbit.com/citicbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/citicbank.com/w/200/h/200', logoSvgl: 'https://www.zhuoxin.hk/ueditor/php/upload/image/20190710/1562726324101210.jpg', brandColor: '#D4000F', swiftBic: 'CIBKCNBJ', notes: 'National Joint-Stock' },
  { id: 8, slug: 'SPDB', name: 'Shanghai Pudong Development Bank', nameLocal: '浦发银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'spdb.com.cn', logoClearbit: 'https://logo.clearbit.com/spdb.com.cn', logoBrandfetch: 'https://cdn.brandfetch.io/spdb.com.cn/w/200/h/200', brandColor: '#003087', swiftBic: 'FDBSCNBH', notes: 'National Joint-Stock' },
  { id: 9, slug: 'Minsheng', name: 'China Minsheng Bank', nameLocal: '民生银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'cmbc.com.cn', logoClearbit: 'https://logo.clearbit.com/cmbc.com.cn', logoBrandfetch: 'https://cdn.brandfetch.io/cmbc.com.cn/w/200/h/200', logoSvgl: 'https://cdn-1.webcatalog.io/catalog/cmbc-cn/cmbc-cn-icon-filled-256.png?v=1717038325015', brandColor: '#003E87', swiftBic: 'MSBCCNBJ', notes: 'National Joint-Stock' },
  { id: 10, slug: 'PingAnBank', name: 'Ping An Bank', nameLocal: '平安银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'bank.pingan.com', logoClearbit: 'https://logo.clearbit.com/bank.pingan.com', logoBrandfetch: 'https://cdn.brandfetch.io/bank.pingan.com/w/200/h/200', brandColor: '#F5820A', swiftBic: 'SZDBCNBS', notes: 'National Joint-Stock' },
  { id: 11, slug: 'Everbright', name: 'China Everbright Bank', nameLocal: '光大银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'cebbank.com', logoClearbit: 'https://logo.clearbit.com/cebbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/cebbank.com/w/200/h/200', brandColor: '#C00C1A', swiftBic: 'EVERCNBJ', notes: 'National Joint-Stock' },
  { id: 12, slug: 'CGB', name: 'Guangfa Bank', nameLocal: '广发银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'cgbchina.com.cn', logoClearbit: 'https://logo.clearbit.com/cgbchina.com.cn', logoBrandfetch: 'https://cdn.brandfetch.io/cgbchina.com.cn/w/200/h/200', brandColor: '#EF3524', swiftBic: 'GDBACNBJ', notes: 'National Joint-Stock' },
  { id: 13, slug: 'HXB', name: 'Hua Xia Bank', nameLocal: '华夏银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'hxb.com.cn', logoClearbit: 'https://logo.clearbit.com/hxb.com.cn', logoBrandfetch: 'https://cdn.brandfetch.io/hxb.com.cn/w/200/h/200', brandColor: '#C8161D', swiftBic: 'HXBKCNBJ', notes: 'National Joint-Stock' },
  { id: 14, slug: 'ZheshangBank', name: 'Zheshang Bank', nameLocal: '浙商银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'czbank.com', logoClearbit: 'https://logo.clearbit.com/czbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/czbank.com/w/200/h/200', logoSvgl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHfwSFvwoEDJGkZz-INmiSgVx5pIwjfEBujg&s', brandColor: '#0052A5', swiftBic: 'ZBESCNB1', notes: 'Regional' },
  { id: 15, slug: 'NingboBank', name: 'Ningbo Bank', nameLocal: '宁波银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'nbcb.cn', logoClearbit: 'https://logo.clearbit.com/nbcb.cn', logoBrandfetch: 'https://cdn.brandfetch.io/nbcb.cn/w/200/h/200', brandColor: '#C20E1A', swiftBic: 'BKCBCN2N', notes: 'Regional' },
  { id: 16, slug: 'NanjingBank', name: 'Nanjing Bank', nameLocal: '南京银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'njcb.com.cn', logoClearbit: 'https://logo.clearbit.com/njcb.com.cn', logoBrandfetch: 'https://cdn.brandfetch.io/njcb.com.cn/w/200/h/200', brandColor: '#005BAC', swiftBic: 'NJCBCNB2', notes: 'Regional' },
  { id: 17, slug: 'BeijingBank', name: 'Bank of Beijing', nameLocal: '北京银行', type: 'bank', subtype: 'commercial_bank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'bankofbeijing.com.cn', logoClearbit: 'https://logo.clearbit.com/bankofbeijing.com.cn', logoBrandfetch: 'https://cdn.brandfetch.io/bankofbeijing.com.cn/w/200/h/200', brandColor: '#CC0000', swiftBic: 'BKBKCNBJ', notes: 'Regional' },
  { id: 18, slug: 'WeBank', name: 'WeBank', nameLocal: '微众银行', type: 'bank', subtype: 'neobank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'webank.com', logoClearbit: 'https://logo.clearbit.com/webank.com', logoBrandfetch: 'https://cdn.brandfetch.io/webank.com/w/200/h/200', logoSvgl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYsieZKvVFTmSVUdU-DMkIhKvDuKo0umQd-Q&s', brandColor: '#38A3FF', notes: 'Internet Bank; backed by Tencent' },
  { id: 19, slug: 'MyBank', name: 'MYbank', nameLocal: '网商银行', type: 'bank', subtype: 'neobank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'mybank.cn', logoClearbit: 'https://logo.clearbit.com/mybank.cn', logoBrandfetch: 'https://cdn.brandfetch.io/mybank.cn/w/200/h/200', logoSvgl: 'https://p0.qhimg.com/t11cede5e7b81aecc298904d22b.png', brandColor: '#FF7100', notes: 'Internet Bank; backed by Ant Group' },
  { id: 20, slug: 'AiBank', name: 'AIBank', nameLocal: '百信银行', type: 'bank', subtype: 'neobank', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'aibank.com', logoClearbit: 'https://logo.clearbit.com/aibank.com', logoBrandfetch: 'https://cdn.brandfetch.io/aibank.com/w/200/h/200', logoSvgl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmEZlaIxUBuuavljGkqN2z6LibHwNhOWV4cw&s', brandColor: '#1B6FBE', notes: 'Internet Bank; backed by Baidu' },
  { id: 100, slug: 'Alipay', name: 'Alipay', nameLocal: '支付宝', type: 'wallet', subtype: 'mobile_payment', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'alipay.com', logoClearbit: 'https://logo.clearbit.com/alipay.com', logoBrandfetch: 'https://cdn.brandfetch.io/alipay.com/w/200/h/200', logoSvgl: 'https://svgl.app/library/alipay.svg', brandColor: '#1677FF', notes: 'Ant Group; 1B+ users' },
  { id: 101, slug: 'WeChatPay', name: 'WeChat Pay', nameLocal: '微信支付', type: 'wallet', subtype: 'mobile_payment', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'weixin.qq.com', logoClearbit: 'https://logo.clearbit.com/weixin.qq.com', logoBrandfetch: 'https://cdn.brandfetch.io/weixin.qq.com/w/200/h/200', logoSvgl: 'https://st.moneydata.hk/res/mojo_static/72a34d94668f7407912647232444279f.png', brandColor: '#07C160', notes: 'Tencent; 900M+ users' },
  { id: 102, slug: 'UnionPayQuickPass', name: 'UnionPay QuickPass', nameLocal: '银联云闪付', type: 'wallet', subtype: 'mobile_payment', country: 'China', region: 'East Asia', currency: 'CNY', domain: 'unionpayintl.com', logoClearbit: 'https://logo.clearbit.com/unionpayintl.com', logoBrandfetch: 'https://cdn.brandfetch.io/unionpayintl.com/w/200/h/200', logoSvgl: 'https://play-lh.googleusercontent.com/_KMxe53g6yqPsRPpwjsekvz8dZxZ0xwOdGnIETdCBSErM9HV0hcpz2fP9tL99Z1gnw', brandColor: '#E21328', notes: 'China UnionPay NFC & QR' },
  { id: 21, slug: 'JPMorgan', name: 'JPMorgan Chase', nameLocal: '摩根大通银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'jpmorganchase.com', logoClearbit: 'https://logo.clearbit.com/jpmorganchase.com', logoBrandfetch: 'https://cdn.brandfetch.io/jpmorganchase.com/w/200/h/200', brandColor: '#003087', swiftBic: 'CHASUS33', notes: 'Largest US bank' },
  { id: 22, slug: 'BankOfAmerica', name: 'Bank of America', nameLocal: '美国银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'bankofamerica.com', logoClearbit: 'https://logo.clearbit.com/bankofamerica.com', logoBrandfetch: 'https://cdn.brandfetch.io/bankofamerica.com/w/200/h/200', brandColor: '#E31837', swiftBic: 'BOFAUS3N' },
  { id: 23, slug: 'Citibank', name: 'Citibank', nameLocal: '花旗银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'citi.com', logoClearbit: 'https://logo.clearbit.com/citi.com', logoBrandfetch: 'https://cdn.brandfetch.io/citi.com/w/200/h/200', brandColor: '#003B8E', swiftBic: 'CITIUS33' },
  { id: 24, slug: 'WellsFargo', name: 'Wells Fargo', nameLocal: '富国银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'wellsfargo.com', logoClearbit: 'https://logo.clearbit.com/wellsfargo.com', logoBrandfetch: 'https://cdn.brandfetch.io/wellsfargo.com/w/200/h/200', brandColor: '#CD1409', swiftBic: 'WFBIUS6S' },
  { id: 25, slug: 'GoldmanSachs', name: 'Goldman Sachs', nameLocal: '高盛银行', type: 'bank', subtype: 'investment_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'goldmansachs.com', logoClearbit: 'https://logo.clearbit.com/goldmansachs.com', logoBrandfetch: 'https://cdn.brandfetch.io/goldmansachs.com/w/200/h/200', brandColor: '#7399C6', swiftBic: 'GSCMUS33' },
  { id: 26, slug: 'MorganStanley', name: 'Morgan Stanley', nameLocal: '摩根士丹利', type: 'bank', subtype: 'investment_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'morganstanley.com', logoClearbit: 'https://logo.clearbit.com/morganstanley.com', logoBrandfetch: 'https://cdn.brandfetch.io/morganstanley.com/w/200/h/200', brandColor: '#003B8E', swiftBic: 'MSNYUS33' },
  { id: 27, slug: 'CapitalOne', name: 'Capital One', nameLocal: '第一资本银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'capitalone.com', logoClearbit: 'https://logo.clearbit.com/capitalone.com', logoBrandfetch: 'https://cdn.brandfetch.io/capitalone.com/w/200/h/200', brandColor: '#004977', swiftBic: 'HIBKUS44' },
  { id: 28, slug: 'PNC', name: 'PNC Bank', nameLocal: 'PNC银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'pnc.com', logoClearbit: 'https://logo.clearbit.com/pnc.com', logoBrandfetch: 'https://cdn.brandfetch.io/pnc.com/w/200/h/200', brandColor: '#F58025', swiftBic: 'PNCCUS33' },
  { id: 29, slug: 'Truist', name: 'Truist Bank', nameLocal: 'Truist银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'truist.com', logoClearbit: 'https://logo.clearbit.com/truist.com', logoBrandfetch: 'https://cdn.brandfetch.io/truist.com/w/200/h/200', brandColor: '#5429B5', swiftBic: 'BRBTUS33', notes: 'Merger of BB&T and SunTrust' },
  { id: 30, slug: 'USBank', name: 'U.S. Bank', nameLocal: '美国合众银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'usbank.com', logoClearbit: 'https://logo.clearbit.com/usbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/usbank.com/w/200/h/200', brandColor: '#0063A5', swiftBic: 'USBKUS44' },
  { id: 31, slug: 'TDBank', name: 'TD Bank', nameLocal: '道明银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'tdbank.com', logoClearbit: 'https://logo.clearbit.com/tdbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/tdbank.com/w/200/h/200', brandColor: '#2B8739', swiftBic: 'TDOMCATTTOR', notes: 'Canada-owned US subsidiary' },
  { id: 32, slug: 'CharlesSchwab', name: 'Charles Schwab Bank', nameLocal: '嘉信理财银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'schwab.com', logoClearbit: 'https://logo.clearbit.com/schwab.com', logoBrandfetch: 'https://cdn.brandfetch.io/schwab.com/w/200/h/200', brandColor: '#00A0DF', swiftBic: 'SCHBUS6S' },
  { id: 33, slug: 'AllyBank', name: 'Ally Bank', nameLocal: 'Ally银行', type: 'bank', subtype: 'neobank', country: 'United States', region: 'North America', currency: 'USD', domain: 'ally.com', logoClearbit: 'https://logo.clearbit.com/ally.com', logoBrandfetch: 'https://cdn.brandfetch.io/ally.com/w/200/h/200', brandColor: '#FF007F', swiftBic: 'ALLBUS33', notes: 'Online-only bank' },
  { id: 34, slug: 'Discover', name: 'Discover Bank', nameLocal: '发现银行', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'discover.com', logoClearbit: 'https://logo.clearbit.com/discover.com', logoBrandfetch: 'https://cdn.brandfetch.io/discover.com/w/200/h/200', brandColor: '#F76300', swiftBic: 'DSCVUS33' },
  { id: 35, slug: 'AmericanExpress', name: 'American Express', nameLocal: '美国运通', type: 'bank', subtype: 'commercial_bank', country: 'United States', region: 'North America', currency: 'USD', domain: 'americanexpress.com', logoClearbit: 'https://logo.clearbit.com/americanexpress.com', logoBrandfetch: 'https://cdn.brandfetch.io/americanexpress.com/w/200/h/200', brandColor: '#016FD0', swiftBic: 'AEIBUS33' },
  { id: 36, slug: 'Chime', name: 'Chime', nameLocal: 'Chime银行', type: 'bank', subtype: 'neobank', country: 'United States', region: 'North America', currency: 'USD', domain: 'chime.com', logoClearbit: 'https://logo.clearbit.com/chime.com', logoBrandfetch: 'https://cdn.brandfetch.io/chime.com/w/200/h/200', brandColor: '#1EC677', notes: 'Neobank; FDIC via Bancorp Bank' },
  { id: 37, slug: 'SoFi', name: 'SoFi Bank', nameLocal: 'SoFi银行', type: 'bank', subtype: 'neobank', country: 'United States', region: 'North America', currency: 'USD', domain: 'sofi.com', logoClearbit: 'https://logo.clearbit.com/sofi.com', logoBrandfetch: 'https://cdn.brandfetch.io/sofi.com/w/200/h/200', brandColor: '#7B2D8B', notes: 'Neobank' },
  { id: 103, slug: 'PayPal', name: 'PayPal', nameLocal: '贝宝', type: 'wallet', subtype: 'p2p_payment', country: 'United States', region: 'North America', currency: 'USD', domain: 'paypal.com', logoClearbit: 'https://logo.clearbit.com/paypal.com', logoBrandfetch: 'https://cdn.brandfetch.io/paypal.com/w/200/h/200', logoSvgl: 'https://svgl.app/library/paypal.svg', brandColor: '#003087', notes: 'Global leader; 400M users' },
  { id: 104, slug: 'Venmo', name: 'Venmo', nameLocal: 'Venmo', type: 'wallet', subtype: 'p2p_payment', country: 'United States', region: 'North America', currency: 'USD', domain: 'venmo.com', logoClearbit: 'https://logo.clearbit.com/venmo.com', logoBrandfetch: 'https://cdn.brandfetch.io/venmo.com/w/200/h/200', brandColor: '#008CFF', notes: 'PayPal subsidiary; popular with millennials' },
  { id: 105, slug: 'CashApp', name: 'Cash App', nameLocal: 'Cash App', type: 'wallet', subtype: 'p2p_payment', country: 'United States', region: 'North America', currency: 'USD', domain: 'cash.app', logoClearbit: 'https://logo.clearbit.com/cash.app', logoBrandfetch: 'https://cdn.brandfetch.io/cash.app/w/200/h/200', brandColor: '#00D64F', notes: 'Block Inc.' },
  { id: 106, slug: 'Stripe', name: 'Stripe', nameLocal: 'Stripe', type: 'wallet', subtype: 'payment_gateway', country: 'United States', region: 'North America', currency: 'USD', domain: 'stripe.com', logoClearbit: 'https://logo.clearbit.com/stripe.com', logoBrandfetch: 'https://cdn.brandfetch.io/stripe.com/w/200/h/200', logoSvgl: 'https://svgl.app/library/stripe.svg', brandColor: '#635BFF', notes: 'Developer-first payments' },
  { id: 107, slug: 'ApplePay', name: 'Apple Pay', nameLocal: '苹果支付', type: 'wallet', subtype: 'mobile_payment', country: 'United States', region: 'North America', currency: 'USD', domain: 'apple.com', logoClearbit: 'https://logo.clearbit.com/apple.com', logoBrandfetch: 'https://cdn.brandfetch.io/apple.com/w/200/h/200', brandColor: '#000000', notes: 'NFC-based; 500M+ users' },
  { id: 108, slug: 'GooglePay', name: 'Google Pay', nameLocal: '谷歌支付', type: 'wallet', subtype: 'mobile_payment', country: 'United States', region: 'North America', currency: 'USD', domain: 'pay.google.com', logoClearbit: 'https://logo.clearbit.com/pay.google.com', logoBrandfetch: 'https://cdn.brandfetch.io/pay.google.com/w/200/h/200', brandColor: '#4285F4' },
  { id: 109, slug: 'AmazonPay', name: 'Amazon Pay', nameLocal: '亚马逊支付', type: 'wallet', subtype: 'payment_gateway', country: 'United States', region: 'North America', currency: 'USD', domain: 'pay.amazon.com', logoClearbit: 'https://logo.clearbit.com/pay.amazon.com', logoBrandfetch: 'https://cdn.brandfetch.io/pay.amazon.com/w/200/h/200', brandColor: '#FF9900' },
  { id: 110, slug: 'Zelle', name: 'Zelle', nameLocal: 'Zelle', type: 'wallet', subtype: 'p2p_payment', country: 'United States', region: 'North America', currency: 'USD', domain: 'zellepay.com', logoClearbit: 'https://logo.clearbit.com/zellepay.com', logoBrandfetch: 'https://cdn.brandfetch.io/zellepay.com/w/200/h/200', brandColor: '#6D1ED4', notes: 'Bank-backed P2P network' },
  { id: 111, slug: 'Square', name: 'Square', nameLocal: 'Square', type: 'wallet', subtype: 'payment_gateway', country: 'United States', region: 'North America', currency: 'USD', domain: 'squareup.com', logoClearbit: 'https://logo.clearbit.com/squareup.com', logoBrandfetch: 'https://cdn.brandfetch.io/squareup.com/w/200/h/200', brandColor: '#3E4348', notes: 'Point-of-sale & payments' },
  { id: 112, slug: 'Klarna', name: 'Klarna', nameLocal: 'Klarna', type: 'wallet', subtype: 'bnpl', country: 'United States', region: 'North America', currency: 'USD', domain: 'klarna.com', logoClearbit: 'https://logo.clearbit.com/klarna.com', logoBrandfetch: 'https://cdn.brandfetch.io/klarna.com/w/200/h/200', logoSvgl: 'https://svgl.app/library/klarna.svg', brandColor: '#FFB3C7', notes: 'Swedish BNPL global' },
  { id: 113, slug: 'Affirm', name: 'Affirm', nameLocal: 'Affirm', type: 'wallet', subtype: 'bnpl', country: 'United States', region: 'North America', currency: 'USD', domain: 'affirm.com', logoClearbit: 'https://logo.clearbit.com/affirm.com', logoBrandfetch: 'https://cdn.brandfetch.io/affirm.com/w/200/h/200', brandColor: '#0FA0EA', notes: 'BNPL leader' },
  { id: 141, slug: 'Coinbase', name: 'Coinbase', nameLocal: 'Coinbase', type: 'wallet', subtype: 'crypto_payment', country: 'United States', region: 'North America', currency: 'USD', domain: 'coinbase.com', logoClearbit: 'https://logo.clearbit.com/coinbase.com', logoBrandfetch: 'https://cdn.brandfetch.io/coinbase.com/w/200/h/200', logoSvgl: 'https://svgl.app/library/coinbase.svg', brandColor: '#0052FF', notes: 'Largest US crypto exchange' },
  { id: 38, slug: 'HSBC', name: 'HSBC', nameLocal: '汇丰银行', type: 'bank', subtype: 'commercial_bank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'hsbc.com', logoClearbit: 'https://logo.clearbit.com/hsbc.com', logoBrandfetch: 'https://cdn.brandfetch.io/hsbc.com/w/200/h/200', brandColor: '#DB0011', swiftBic: 'MIDLGB22', notes: 'Global HQ in London' },
  { id: 39, slug: 'Barclays', name: 'Barclays', nameLocal: '巴克莱银行', type: 'bank', subtype: 'commercial_bank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'barclays.com', logoClearbit: 'https://logo.clearbit.com/barclays.com', logoBrandfetch: 'https://cdn.brandfetch.io/barclays.com/w/200/h/200', brandColor: '#00AEEF', swiftBic: 'BARCGB22' },
  { id: 40, slug: 'Lloyds', name: 'Lloyds Bank', nameLocal: '劳埃德银行', type: 'bank', subtype: 'commercial_bank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'lloydsbank.com', logoClearbit: 'https://logo.clearbit.com/lloydsbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/lloydsbank.com/w/200/h/200', brandColor: '#006A4E', swiftBic: 'LOYDGB2L' },
  { id: 41, slug: 'NatWest', name: 'NatWest', nameLocal: '国民西敏寺银行', type: 'bank', subtype: 'commercial_bank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'natwest.com', logoClearbit: 'https://logo.clearbit.com/natwest.com', logoBrandfetch: 'https://cdn.brandfetch.io/natwest.com/w/200/h/200', brandColor: '#42145F', swiftBic: 'NWBKGB2L' },
  { id: 42, slug: 'StanChart', name: 'Standard Chartered', nameLocal: '渣打银行', type: 'bank', subtype: 'commercial_bank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'sc.com', logoClearbit: 'https://logo.clearbit.com/sc.com', logoBrandfetch: 'https://cdn.brandfetch.io/sc.com/w/200/h/200', brandColor: '#0072AA', swiftBic: 'SCBLGB2L', notes: 'HQ London; major in Asia' },
  { id: 43, slug: 'Monzo', name: 'Monzo', nameLocal: 'Monzo银行', type: 'bank', subtype: 'neobank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'monzo.com', logoClearbit: 'https://logo.clearbit.com/monzo.com', logoBrandfetch: 'https://cdn.brandfetch.io/monzo.com/w/200/h/200', brandColor: '#FF3464', swiftBic: 'MONZGB2L', notes: 'UK neobank unicorn' },
  { id: 44, slug: 'Starling', name: 'Starling Bank', nameLocal: 'Starling银行', type: 'bank', subtype: 'neobank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'starlingbank.com', logoClearbit: 'https://logo.clearbit.com/starlingbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/starlingbank.com/w/200/h/200', brandColor: '#6935D3', notes: 'UK neobank' },
  { id: 45, slug: 'Revolut', name: 'Revolut', nameLocal: 'Revolut', type: 'wallet', subtype: 'neobank', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'revolut.com', logoClearbit: 'https://logo.clearbit.com/revolut.com', logoBrandfetch: 'https://cdn.brandfetch.io/revolut.com/w/200/h/200', logoSvgl: 'https://svgl.app/library/revolut.svg', brandColor: '#191C1F', notes: 'Super-app; 40M+ users' },
  { id: 46, slug: 'Wise', name: 'Wise', nameLocal: 'Wise', type: 'wallet', subtype: 'p2p_payment', country: 'United Kingdom', region: 'Western Europe', currency: 'GBP', domain: 'wise.com', logoClearbit: 'https://logo.clearbit.com/wise.com', logoBrandfetch: 'https://cdn.brandfetch.io/wise.com/w/200/h/200', logoSvgl: 'https://svgl.app/library/wise.svg', brandColor: '#9FE870', notes: 'International transfers' },
  { id: 47, slug: 'DBS', name: 'DBS Bank', nameLocal: '星展银行', type: 'bank', subtype: 'commercial_bank', country: 'Singapore', region: 'Southeast Asia', currency: 'SGD', domain: 'dbs.com', logoClearbit: 'https://logo.clearbit.com/dbs.com', logoBrandfetch: 'https://cdn.brandfetch.io/dbs.com/w/200/h/200', brandColor: '#DD0000', swiftBic: 'DBSSSGSG', notes: "Singapore's largest bank" },
  { id: 48, slug: 'OCBC', name: 'OCBC Bank', nameLocal: '华侨银行', type: 'bank', subtype: 'commercial_bank', country: 'Singapore', region: 'Southeast Asia', currency: 'SGD', domain: 'ocbc.com', logoClearbit: 'https://logo.clearbit.com/ocbc.com', logoBrandfetch: 'https://cdn.brandfetch.io/ocbc.com/w/200/h/200', brandColor: '#FF0000', swiftBic: 'OCBCSGSG' },
  { id: 49, slug: 'UOB', name: 'UOB', nameLocal: '大华银行', type: 'bank', subtype: 'commercial_bank', country: 'Singapore', region: 'Southeast Asia', currency: 'SGD', domain: 'uobgroup.com', logoClearbit: 'https://logo.clearbit.com/uobgroup.com', logoBrandfetch: 'https://cdn.brandfetch.io/uobgroup.com/w/200/h/200', brandColor: '#005BAC', swiftBic: 'UOVBSGSG' },
  { id: 143, slug: 'CryptoCom', name: 'Crypto.com Pay', nameLocal: 'Crypto.com支付', type: 'wallet', subtype: 'crypto_payment', country: 'Singapore', region: 'Southeast Asia', currency: 'USD', domain: 'crypto.com', logoClearbit: 'https://logo.clearbit.com/crypto.com', logoBrandfetch: 'https://cdn.brandfetch.io/crypto.com/w/200/h/200', brandColor: '#002D74', notes: 'Crypto.com payment layer' },
  { id: 50, slug: 'Maybank', name: 'Maybank', nameLocal: '马来亚银行', type: 'bank', subtype: 'commercial_bank', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'maybank.com', logoClearbit: 'https://logo.clearbit.com/maybank.com', logoBrandfetch: 'https://cdn.brandfetch.io/maybank.com/w/200/h/200', brandColor: '#FFD100', swiftBic: 'MBBEMYKL', notes: 'Largest Malaysian bank' },
  { id: 51, slug: 'CIMB', name: 'CIMB Bank', nameLocal: '联昌银行', type: 'bank', subtype: 'commercial_bank', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'cimb.com', logoClearbit: 'https://logo.clearbit.com/cimb.com', logoBrandfetch: 'https://cdn.brandfetch.io/cimb.com/w/200/h/200', brandColor: '#C5192D', swiftBic: 'CIBBMYKL' },
  { id: 52, slug: 'PublicBank', name: 'Public Bank', nameLocal: '大众银行', type: 'bank', subtype: 'commercial_bank', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'publicbankgroup.com', logoClearbit: 'https://logo.clearbit.com/publicbankgroup.com', logoBrandfetch: 'https://cdn.brandfetch.io/publicbankgroup.com/w/200/h/200', brandColor: '#005BAC', swiftBic: 'PBBEMYKL' },
  { id: 53, slug: 'RHB', name: 'RHB Bank', nameLocal: '兴业银行', type: 'bank', subtype: 'commercial_bank', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'rhbgroup.com', logoClearbit: 'https://logo.clearbit.com/rhbgroup.com', logoBrandfetch: 'https://cdn.brandfetch.io/rhbgroup.com/w/200/h/200', brandColor: '#004A97', swiftBic: 'RHBBMYKL' },
  { id: 54, slug: 'HongLeong', name: 'Hong Leong Bank', nameLocal: '丰隆银行', type: 'bank', subtype: 'commercial_bank', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'hlb.com.my', logoClearbit: 'https://logo.clearbit.com/hlb.com.my', logoBrandfetch: 'https://cdn.brandfetch.io/hlb.com.my/w/200/h/200', brandColor: '#0072BC', swiftBic: 'HLBBMYKL' },
  { id: 55, slug: 'AmBank', name: 'AmBank', nameLocal: 'AmBank', type: 'bank', subtype: 'commercial_bank', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'ambankgroup.com', logoClearbit: 'https://logo.clearbit.com/ambankgroup.com', logoBrandfetch: 'https://cdn.brandfetch.io/ambankgroup.com/w/200/h/200', brandColor: '#E21328', swiftBic: 'ARBKMYKL' },
  { id: 114, slug: 'TouchNGo', name: "Touch 'n Go eWallet", nameLocal: '一触即通电子钱包', type: 'wallet', subtype: 'mobile_payment', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'tngdigital.com.my', logoClearbit: 'https://logo.clearbit.com/tngdigital.com.my', logoBrandfetch: 'https://cdn.brandfetch.io/tngdigital.com.my/w/200/h/200', logoSvgl: 'https://d1eipm3vz40hy0.cloudfront.net/images/Customer+Stories+/TNG_Digital/TNG_logo_4.png', brandColor: '#00AEF0', notes: "Malaysia's most popular e-wallet" },
  { id: 115, slug: 'Boost', name: 'Boost', nameLocal: 'Boost', type: 'wallet', subtype: 'mobile_payment', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'myboost.com.my', logoClearbit: 'https://logo.clearbit.com/myboost.com.my', logoBrandfetch: 'https://cdn.brandfetch.io/myboost.com.my/w/200/h/200', brandColor: '#FF4040', notes: 'Axiata subsidiary' },
  { id: 116, slug: 'ShopeePay', name: 'ShopeePay', nameLocal: 'ShopeePay', type: 'wallet', subtype: 'mobile_payment', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'shopee.com.my', logoClearbit: 'https://logo.clearbit.com/shopee.com.my', logoBrandfetch: 'https://cdn.brandfetch.io/shopee.com.my/w/200/h/200', brandColor: '#EE4D2D', notes: 'Sea Group; tied to Shopee' },
  { id: 117, slug: 'BigPay', name: 'BigPay', nameLocal: 'BigPay', type: 'wallet', subtype: 'neobank', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'bigpayme.com', logoClearbit: 'https://logo.clearbit.com/bigpayme.com', logoBrandfetch: 'https://cdn.brandfetch.io/bigpayme.com/w/200/h/200', brandColor: '#EB5757', notes: 'AirAsia Group fintech' },
  { id: 118, slug: 'GrabPayMY', name: 'GrabPay', nameLocal: 'GrabPay', type: 'wallet', subtype: 'mobile_payment', country: 'Malaysia', region: 'Southeast Asia', currency: 'MYR', domain: 'grab.com', logoClearbit: 'https://logo.clearbit.com/grab.com', logoBrandfetch: 'https://cdn.brandfetch.io/grab.com/w/200/h/200', brandColor: '#00B14F', notes: 'Grab super-app wallet' },
  { id: 56, slug: 'SBI', name: 'State Bank of India', nameLocal: '印度国家银行', type: 'bank', subtype: 'commercial_bank', country: 'India', region: 'South Asia', currency: 'INR', domain: 'sbi.co.in', logoClearbit: 'https://logo.clearbit.com/sbi.co.in', logoBrandfetch: 'https://cdn.brandfetch.io/sbi.co.in/w/200/h/200', brandColor: '#2D5FA6', swiftBic: 'SBININBB', notes: "India's largest bank" },
  { id: 57, slug: 'HDFCBank', name: 'HDFC Bank', nameLocal: 'HDFC银行', type: 'bank', subtype: 'commercial_bank', country: 'India', region: 'South Asia', currency: 'INR', domain: 'hdfcbank.com', logoClearbit: 'https://logo.clearbit.com/hdfcbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/hdfcbank.com/w/200/h/200', brandColor: '#004C8F', swiftBic: 'HDFCINBB' },
  { id: 58, slug: 'ICICIBank', name: 'ICICI Bank', nameLocal: 'ICICI银行', type: 'bank', subtype: 'commercial_bank', country: 'India', region: 'South Asia', currency: 'INR', domain: 'icicibank.com', logoClearbit: 'https://logo.clearbit.com/icicibank.com', logoBrandfetch: 'https://cdn.brandfetch.io/icicibank.com/w/200/h/200', brandColor: '#F58220', swiftBic: 'ICICIN BB' },
  { id: 59, slug: 'AxisBank', name: 'Axis Bank', nameLocal: 'Axis银行', type: 'bank', subtype: 'commercial_bank', country: 'India', region: 'South Asia', currency: 'INR', domain: 'axisbank.com', logoClearbit: 'https://logo.clearbit.com/axisbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/axisbank.com/w/200/h/200', brandColor: '#800000', swiftBic: 'AXISINBB' },
  { id: 60, slug: 'KotakBank', name: 'Kotak Mahindra Bank', nameLocal: 'Kotak银行', type: 'bank', subtype: 'commercial_bank', country: 'India', region: 'South Asia', currency: 'INR', domain: 'kotak.com', logoClearbit: 'https://logo.clearbit.com/kotak.com', logoBrandfetch: 'https://cdn.brandfetch.io/kotak.com/w/200/h/200', brandColor: '#ED1C24', swiftBic: 'KKBKINBB' },
  { id: 125, slug: 'Paytm', name: 'Paytm', nameLocal: 'Paytm', type: 'wallet', subtype: 'mobile_payment', country: 'India', region: 'South Asia', currency: 'INR', domain: 'paytm.com', logoClearbit: 'https://logo.clearbit.com/paytm.com', logoBrandfetch: 'https://cdn.brandfetch.io/paytm.com/w/200/h/200', brandColor: '#002970', notes: "India's OG fintech; 350M users" },
  { id: 126, slug: 'PhonePe', name: 'PhonePe', nameLocal: 'PhonePe', type: 'wallet', subtype: 'mobile_payment', country: 'India', region: 'South Asia', currency: 'INR', domain: 'phonepe.com', logoClearbit: 'https://logo.clearbit.com/phonepe.com', logoBrandfetch: 'https://cdn.brandfetch.io/phonepe.com/w/200/h/200', brandColor: '#5F259F', notes: 'Walmart-owned; India UPI leader' },
  { id: 127, slug: 'GPay', name: 'Google Pay India', nameLocal: '谷歌支付(印度)', type: 'wallet', subtype: 'mobile_payment', country: 'India', region: 'South Asia', currency: 'INR', domain: 'pay.google.com', logoClearbit: 'https://logo.clearbit.com/pay.google.com', logoBrandfetch: 'https://cdn.brandfetch.io/pay.google.com/w/200/h/200', brandColor: '#4285F4', notes: "UPI-based; India's top payment app" },
  { id: 61, slug: 'MUFG', name: 'MUFG Bank', nameLocal: '三菱UFJ银行', type: 'bank', subtype: 'commercial_bank', country: 'Japan', region: 'East Asia', currency: 'JPY', domain: 'mufg.jp', logoClearbit: 'https://logo.clearbit.com/mufg.jp', logoBrandfetch: 'https://cdn.brandfetch.io/mufg.jp/w/200/h/200', brandColor: '#820000', swiftBic: 'BOTKJPJT', notes: 'Largest Japanese bank' },
  { id: 62, slug: 'SMBC', name: 'SMBC', nameLocal: '三井住友银行', type: 'bank', subtype: 'commercial_bank', country: 'Japan', region: 'East Asia', currency: 'JPY', domain: 'smbc.co.jp', logoClearbit: 'https://logo.clearbit.com/smbc.co.jp', logoBrandfetch: 'https://cdn.brandfetch.io/smbc.co.jp/w/200/h/200', brandColor: '#005BAC', swiftBic: 'SMBCJPJT' },
  { id: 63, slug: 'Mizuho', name: 'Mizuho Bank', nameLocal: '瑞穗银行', type: 'bank', subtype: 'commercial_bank', country: 'Japan', region: 'East Asia', currency: 'JPY', domain: 'mizuho-fg.co.jp', logoClearbit: 'https://logo.clearbit.com/mizuho-fg.co.jp', logoBrandfetch: 'https://cdn.brandfetch.io/mizuho-fg.co.jp/w/200/h/200', brandColor: '#003087', swiftBic: 'MHCBJPJT' },
  { id: 64, slug: 'RakutenBank', name: 'Rakuten Bank', nameLocal: '乐天银行', type: 'bank', subtype: 'neobank', country: 'Japan', region: 'East Asia', currency: 'JPY', domain: 'rakuten-bank.co.jp', logoClearbit: 'https://logo.clearbit.com/rakuten-bank.co.jp', logoBrandfetch: 'https://cdn.brandfetch.io/rakuten-bank.co.jp/w/200/h/200', brandColor: '#BF0000', swiftBic: 'RAKTJPJT', notes: 'Online bank' },
  { id: 119, slug: 'PayPay', name: 'PayPay', nameLocal: 'PayPay', type: 'wallet', subtype: 'mobile_payment', country: 'Japan', region: 'East Asia', currency: 'JPY', domain: 'paypay.ne.jp', logoClearbit: 'https://logo.clearbit.com/paypay.ne.jp', logoBrandfetch: 'https://cdn.brandfetch.io/paypay.ne.jp/w/200/h/200', brandColor: '#FF0033', notes: "Japan's #1 QR payment; 60M users" },
  { id: 120, slug: 'LinePay', name: 'LINE Pay', nameLocal: 'LINE Pay', type: 'wallet', subtype: 'mobile_payment', country: 'Japan', region: 'East Asia', currency: 'JPY', domain: 'line.me', logoClearbit: 'https://logo.clearbit.com/line.me', logoBrandfetch: 'https://cdn.brandfetch.io/line.me/w/200/h/200', brandColor: '#00B900', notes: 'LINE messaging + payments' },
  { id: 65, slug: 'KBKookmin', name: 'KB Kookmin Bank', nameLocal: 'KB国民银行', type: 'bank', subtype: 'commercial_bank', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'kbfg.com', logoClearbit: 'https://logo.clearbit.com/kbfg.com', logoBrandfetch: 'https://cdn.brandfetch.io/kbfg.com/w/200/h/200', brandColor: '#FFB500', swiftBic: 'CZNBKRSE' },
  { id: 66, slug: 'ShinhanBank', name: 'Shinhan Bank', nameLocal: '新韩银行', type: 'bank', subtype: 'commercial_bank', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'shinhan.com', logoClearbit: 'https://logo.clearbit.com/shinhan.com', logoBrandfetch: 'https://cdn.brandfetch.io/shinhan.com/w/200/h/200', brandColor: '#0046FF', swiftBic: 'SHBKKRSE' },
  { id: 67, slug: 'HanaBank', name: 'Hana Bank', nameLocal: '韩亚银行', type: 'bank', subtype: 'commercial_bank', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'hanabank.com', logoClearbit: 'https://logo.clearbit.com/hanabank.com', logoBrandfetch: 'https://cdn.brandfetch.io/hanabank.com/w/200/h/200', brandColor: '#009900', swiftBic: 'KOEXKRSE' },
  { id: 68, slug: 'WooriBank', name: 'Woori Bank', nameLocal: '友利银行', type: 'bank', subtype: 'commercial_bank', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'wooribank.com', logoClearbit: 'https://logo.clearbit.com/wooribank.com', logoBrandfetch: 'https://cdn.brandfetch.io/wooribank.com/w/200/h/200', brandColor: '#005BAC', swiftBic: 'HVBKKRSE' },
  { id: 69, slug: 'KakaoBank', name: 'KakaoBank', nameLocal: 'Kakao银行', type: 'bank', subtype: 'neobank', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'kakaobank.com', logoClearbit: 'https://logo.clearbit.com/kakaobank.com', logoBrandfetch: 'https://cdn.brandfetch.io/kakaobank.com/w/200/h/200', brandColor: '#FAE100', notes: 'Mobile-first neobank' },
  { id: 121, slug: 'KakaoPay', name: 'Kakao Pay', nameLocal: 'Kakao Pay', type: 'wallet', subtype: 'mobile_payment', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'kakaopay.com', logoClearbit: 'https://logo.clearbit.com/kakaopay.com', logoBrandfetch: 'https://cdn.brandfetch.io/kakaopay.com/w/200/h/200', brandColor: '#FAE100', notes: 'Kakao super-app; 38M users' },
  { id: 122, slug: 'NaverPay', name: 'Naver Pay', nameLocal: 'Naver Pay', type: 'wallet', subtype: 'mobile_payment', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'naver.com', logoClearbit: 'https://logo.clearbit.com/naver.com', logoBrandfetch: 'https://cdn.brandfetch.io/naver.com/w/200/h/200', brandColor: '#03C75A', notes: 'Naver search + payments' },
  { id: 123, slug: 'Toss', name: 'Toss', nameLocal: 'Toss', type: 'wallet', subtype: 'neobank', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'toss.im', logoClearbit: 'https://logo.clearbit.com/toss.im', logoBrandfetch: 'https://cdn.brandfetch.io/toss.im/w/200/h/200', brandColor: '#0064FF', notes: "Korea's fintech unicorn" },
  { id: 124, slug: 'SamsungPay', name: 'Samsung Pay', nameLocal: '三星支付', type: 'wallet', subtype: 'mobile_payment', country: 'South Korea', region: 'East Asia', currency: 'KRW', domain: 'samsung.com', logoClearbit: 'https://logo.clearbit.com/samsung.com', logoBrandfetch: 'https://cdn.brandfetch.io/samsung.com/w/200/h/200', brandColor: '#1428A0', notes: 'NFC + MST payment' },
  { id: 70, slug: 'RBC', name: 'Royal Bank of Canada', nameLocal: '加拿大皇家银行', type: 'bank', subtype: 'commercial_bank', country: 'Canada', region: 'North America', currency: 'CAD', domain: 'rbc.com', logoClearbit: 'https://logo.clearbit.com/rbc.com', logoBrandfetch: 'https://cdn.brandfetch.io/rbc.com/w/200/h/200', brandColor: '#003DA5', swiftBic: 'ROYCCAT2' },
  { id: 71, slug: 'TD', name: 'TD Bank', nameLocal: '道明银行', type: 'bank', subtype: 'commercial_bank', country: 'Canada', region: 'North America', currency: 'CAD', domain: 'td.com', logoClearbit: 'https://logo.clearbit.com/td.com', logoBrandfetch: 'https://cdn.brandfetch.io/td.com/w/200/h/200', brandColor: '#34B233', swiftBic: 'TDOMCATTTOR' },
  { id: 72, slug: 'Scotiabank', name: 'Scotiabank', nameLocal: '丰业银行', type: 'bank', subtype: 'commercial_bank', country: 'Canada', region: 'North America', currency: 'CAD', domain: 'scotiabank.com', logoClearbit: 'https://logo.clearbit.com/scotiabank.com', logoBrandfetch: 'https://cdn.brandfetch.io/scotiabank.com/w/200/h/200', brandColor: '#EC111A', swiftBic: 'NOSCCAT2' },
  { id: 73, slug: 'BMO', name: 'BMO', nameLocal: '蒙特利尔银行', type: 'bank', subtype: 'commercial_bank', country: 'Canada', region: 'North America', currency: 'CAD', domain: 'bmo.com', logoClearbit: 'https://logo.clearbit.com/bmo.com', logoBrandfetch: 'https://cdn.brandfetch.io/bmo.com/w/200/h/200', brandColor: '#0073CF', swiftBic: 'BOFMCAM2' },
  { id: 74, slug: 'CIBC', name: 'CIBC', nameLocal: '加拿大帝国商业银行', type: 'bank', subtype: 'commercial_bank', country: 'Canada', region: 'North America', currency: 'CAD', domain: 'cibc.com', logoClearbit: 'https://logo.clearbit.com/cibc.com', logoBrandfetch: 'https://cdn.brandfetch.io/cibc.com/w/200/h/200', brandColor: '#C41F3A', swiftBic: 'CIBCCATT' },
  { id: 75, slug: 'CommBank', name: 'Commonwealth Bank', nameLocal: '联邦银行', type: 'bank', subtype: 'commercial_bank', country: 'Australia', region: 'Oceania', currency: 'AUD', domain: 'commbank.com.au', logoClearbit: 'https://logo.clearbit.com/commbank.com.au', logoBrandfetch: 'https://cdn.brandfetch.io/commbank.com.au/w/200/h/200', brandColor: '#FFD100', swiftBic: 'CTBAAU2S' },
  { id: 76, slug: 'Westpac', name: 'Westpac', nameLocal: '西太平洋银行', type: 'bank', subtype: 'commercial_bank', country: 'Australia', region: 'Oceania', currency: 'AUD', domain: 'westpac.com.au', logoClearbit: 'https://logo.clearbit.com/westpac.com.au', logoBrandfetch: 'https://cdn.brandfetch.io/westpac.com.au/w/200/h/200', brandColor: '#D5002B', swiftBic: 'WPACAU2S' },
  { id: 77, slug: 'ANZ', name: 'ANZ', nameLocal: '澳新银行', type: 'bank', subtype: 'commercial_bank', country: 'Australia', region: 'Oceania', currency: 'AUD', domain: 'anz.com', logoClearbit: 'https://logo.clearbit.com/anz.com', logoBrandfetch: 'https://cdn.brandfetch.io/anz.com/w/200/h/200', brandColor: '#007DBA', swiftBic: 'ANZBAU3M' },
  { id: 78, slug: 'NAB', name: 'NAB', nameLocal: '澳大利亚国民银行', type: 'bank', subtype: 'commercial_bank', country: 'Australia', region: 'Oceania', currency: 'AUD', domain: 'nab.com.au', logoClearbit: 'https://logo.clearbit.com/nab.com.au', logoBrandfetch: 'https://cdn.brandfetch.io/nab.com.au/w/200/h/200', brandColor: '#E21328', swiftBic: 'NATAAU3303M' },
  { id: 79, slug: 'DeutscheBank', name: 'Deutsche Bank', nameLocal: '德意志银行', type: 'bank', subtype: 'commercial_bank', country: 'Germany', region: 'Western Europe', currency: 'EUR', domain: 'db.com', logoClearbit: 'https://logo.clearbit.com/db.com', logoBrandfetch: 'https://cdn.brandfetch.io/db.com/w/200/h/200', brandColor: '#0018A8', swiftBic: 'DEUTDEDB' },
  { id: 80, slug: 'Commerzbank', name: 'Commerzbank', nameLocal: '商业银行', type: 'bank', subtype: 'commercial_bank', country: 'Germany', region: 'Western Europe', currency: 'EUR', domain: 'commerzbank.com', logoClearbit: 'https://logo.clearbit.com/commerzbank.com', logoBrandfetch: 'https://cdn.brandfetch.io/commerzbank.com/w/200/h/200', brandColor: '#FFCC00', swiftBic: 'COBADEFF' },
  { id: 81, slug: 'N26', name: 'N26', nameLocal: 'N26银行', type: 'bank', subtype: 'neobank', country: 'Germany', region: 'Western Europe', currency: 'EUR', domain: 'n26.com', logoClearbit: 'https://logo.clearbit.com/n26.com', logoBrandfetch: 'https://cdn.brandfetch.io/n26.com/w/200/h/200', brandColor: '#1A1A2E', swiftBic: 'NTSBDEB1', notes: 'Pan-European neobank' },
  { id: 82, slug: 'BNPParibas', name: 'BNP Paribas', nameLocal: '法国巴黎银行', type: 'bank', subtype: 'commercial_bank', country: 'France', region: 'Western Europe', currency: 'EUR', domain: 'bnpparibas.com', logoClearbit: 'https://logo.clearbit.com/bnpparibas.com', logoBrandfetch: 'https://cdn.brandfetch.io/bnpparibas.com/w/200/h/200', brandColor: '#009440', swiftBic: 'BNPAFRPP', notes: 'Largest French bank' },
  { id: 83, slug: 'CreditAgricole', name: 'Credit Agricole', nameLocal: '法国农业信贷银行', type: 'bank', subtype: 'cooperative_bank', country: 'France', region: 'Western Europe', currency: 'EUR', domain: 'credit-agricole.com', logoClearbit: 'https://logo.clearbit.com/credit-agricole.com', logoBrandfetch: 'https://cdn.brandfetch.io/credit-agricole.com/w/200/h/200', brandColor: '#00855A', swiftBic: 'AGRIFRPP' },
  { id: 84, slug: 'SocieteGenerale', name: 'Societe Generale', nameLocal: '法国兴业银行', type: 'bank', subtype: 'commercial_bank', country: 'France', region: 'Western Europe', currency: 'EUR', domain: 'societegenerale.com', logoClearbit: 'https://logo.clearbit.com/societegenerale.com', logoBrandfetch: 'https://cdn.brandfetch.io/societegenerale.com/w/200/h/200', brandColor: '#E60028', swiftBic: 'SOGEFRPP' },
  { id: 85, slug: 'UBS', name: 'UBS', nameLocal: '瑞银集团', type: 'bank', subtype: 'investment_bank', country: 'Switzerland', region: 'Western Europe', currency: 'CHF', domain: 'ubs.com', logoClearbit: 'https://logo.clearbit.com/ubs.com', logoBrandfetch: 'https://cdn.brandfetch.io/ubs.com/w/200/h/200', brandColor: '#E30613', swiftBic: 'UBSWCHZH', notes: 'Absorbed Credit Suisse 2023' },
  { id: 86, slug: 'ING', name: 'ING', nameLocal: 'ING银行', type: 'bank', subtype: 'commercial_bank', country: 'Netherlands', region: 'Western Europe', currency: 'EUR', domain: 'ing.com', logoClearbit: 'https://logo.clearbit.com/ing.com', logoBrandfetch: 'https://cdn.brandfetch.io/ing.com/w/200/h/200', brandColor: '#FF6200', swiftBic: 'INGBNL2A' },
  { id: 87, slug: 'ABNAMRO', name: 'ABN AMRO', nameLocal: '荷兰银行', type: 'bank', subtype: 'commercial_bank', country: 'Netherlands', region: 'Western Europe', currency: 'EUR', domain: 'abnamro.com', logoClearbit: 'https://logo.clearbit.com/abnamro.com', logoBrandfetch: 'https://cdn.brandfetch.io/abnamro.com/w/200/h/200', brandColor: '#009286', swiftBic: 'ABNANL2A' },
  { id: 88, slug: 'Rabobank', name: 'Rabobank', nameLocal: '荷兰合作银行', type: 'bank', subtype: 'cooperative_bank', country: 'Netherlands', region: 'Western Europe', currency: 'EUR', domain: 'rabobank.com', logoClearbit: 'https://logo.clearbit.com/rabobank.com', logoBrandfetch: 'https://cdn.brandfetch.io/rabobank.com/w/200/h/200', brandColor: '#FF6200', swiftBic: 'RABONL2U' },
  { id: 89, slug: 'Santander', name: 'Santander', nameLocal: '桑坦德银行', type: 'bank', subtype: 'commercial_bank', country: 'Spain', region: 'Western Europe', currency: 'EUR', domain: 'santander.com', logoClearbit: 'https://logo.clearbit.com/santander.com', logoBrandfetch: 'https://cdn.brandfetch.io/santander.com/w/200/h/200', brandColor: '#EC0000', swiftBic: 'BSCHESMM', notes: 'Largest Spanish bank' },
  { id: 90, slug: 'BBVA', name: 'BBVA', nameLocal: '毕尔巴鄂比斯开银行', type: 'bank', subtype: 'commercial_bank', country: 'Spain', region: 'Western Europe', currency: 'EUR', domain: 'bbva.com', logoClearbit: 'https://logo.clearbit.com/bbva.com', logoBrandfetch: 'https://cdn.brandfetch.io/bbva.com/w/200/h/200', brandColor: '#004B87', swiftBic: 'BBVAESMM' },
  { id: 91, slug: 'UniCredit', name: 'UniCredit', nameLocal: '意大利联合信贷银行', type: 'bank', subtype: 'commercial_bank', country: 'Italy', region: 'Western Europe', currency: 'EUR', domain: 'unicredit.eu', logoClearbit: 'https://logo.clearbit.com/unicredit.eu', logoBrandfetch: 'https://cdn.brandfetch.io/unicredit.eu/w/200/h/200', brandColor: '#DD1D21', swiftBic: 'UNCRITMM' },
  { id: 92, slug: 'IntesaSanpaolo', name: 'Intesa Sanpaolo', nameLocal: '意大利联合圣保罗银行', type: 'bank', subtype: 'commercial_bank', country: 'Italy', region: 'Western Europe', currency: 'EUR', domain: 'intesasanpaolo.com', logoClearbit: 'https://logo.clearbit.com/intesasanpaolo.com', logoBrandfetch: 'https://cdn.brandfetch.io/intesasanpaolo.com/w/200/h/200', brandColor: '#003F8A', swiftBic: 'BCITITIM' },
  { id: 93, slug: 'Nordea', name: 'Nordea', nameLocal: '北欧联合银行', type: 'bank', subtype: 'commercial_bank', country: 'Sweden', region: 'Western Europe', currency: 'SEK', domain: 'nordea.com', logoClearbit: 'https://logo.clearbit.com/nordea.com', logoBrandfetch: 'https://cdn.brandfetch.io/nordea.com/w/200/h/200', brandColor: '#00005E', swiftBic: 'NDEAFIHHXXX', notes: "Nordic region's largest bank" },
  { id: 94, slug: 'SEB', name: 'SEB', nameLocal: '瑞典北欧斯安银行', type: 'bank', subtype: 'commercial_bank', country: 'Sweden', region: 'Western Europe', currency: 'SEK', domain: 'sebgroup.com', logoClearbit: 'https://logo.clearbit.com/sebgroup.com', logoBrandfetch: 'https://cdn.brandfetch.io/sebgroup.com/w/200/h/200', brandColor: '#007AC2', swiftBic: 'ESSESESS' },
  { id: 95, slug: 'DanskeBank', name: 'Danske Bank', nameLocal: '丹斯克银行', type: 'bank', subtype: 'commercial_bank', country: 'Denmark', region: 'Western Europe', currency: 'DKK', domain: 'danskebank.com', logoClearbit: 'https://logo.clearbit.com/danskebank.com', logoBrandfetch: 'https://cdn.brandfetch.io/danskebank.com/w/200/h/200', brandColor: '#003755', swiftBic: 'DABADKKK' },
  { id: 96, slug: 'Itau', name: 'Itaú Unibanco', nameLocal: '伊塔乌联合银行', type: 'bank', subtype: 'commercial_bank', country: 'Brazil', region: 'Latin America', currency: 'BRL', domain: 'itau.com.br', logoClearbit: 'https://logo.clearbit.com/itau.com.br', logoBrandfetch: 'https://cdn.brandfetch.io/itau.com.br/w/200/h/200', brandColor: '#F7941D', swiftBic: 'ITAUBRSP', notes: "Brazil's largest private bank" },
  { id: 97, slug: 'Bradesco', name: 'Bradesco', nameLocal: '布拉德斯科银行', type: 'bank', subtype: 'commercial_bank', country: 'Brazil', region: 'Latin America', currency: 'BRL', domain: 'bradesco.com.br', logoClearbit: 'https://logo.clearbit.com/bradesco.com.br', logoBrandfetch: 'https://cdn.brandfetch.io/bradesco.com.br/w/200/h/200', brandColor: '#CC0000', swiftBic: 'BBDEBRSP' },
  { id: 98, slug: 'BancoDoBrasil', name: 'Banco do Brasil', nameLocal: '巴西银行', type: 'bank', subtype: 'commercial_bank', country: 'Brazil', region: 'Latin America', currency: 'BRL', domain: 'bb.com.br', logoClearbit: 'https://logo.clearbit.com/bb.com.br', logoBrandfetch: 'https://cdn.brandfetch.io/bb.com.br/w/200/h/200', brandColor: '#003DA5', swiftBic: 'BRASBRRJBHE' },
  { id: 99, slug: 'Nubank', name: 'Nubank', nameLocal: 'Nubank', type: 'bank', subtype: 'neobank', country: 'Brazil', region: 'Latin America', currency: 'BRL', domain: 'nu.com.br', logoClearbit: 'https://logo.clearbit.com/nu.com.br', logoBrandfetch: 'https://cdn.brandfetch.io/nu.com.br/w/200/h/200', brandColor: '#820AD1', notes: "Latin America's largest neobank" },
  { id: 137, slug: 'PicPay', name: 'PicPay', nameLocal: 'PicPay', type: 'wallet', subtype: 'mobile_payment', country: 'Brazil', region: 'Latin America', currency: 'BRL', domain: 'picpay.com', logoClearbit: 'https://logo.clearbit.com/picpay.com', logoBrandfetch: 'https://cdn.brandfetch.io/picpay.com/w/200/h/200', brandColor: '#21C25E', notes: "Brazil's popular P2P app" },
  { id: 138, slug: 'PagSeguro', name: 'PagSeguro', nameLocal: 'PagSeguro', type: 'wallet', subtype: 'payment_gateway', country: 'Brazil', region: 'Latin America', currency: 'BRL', domain: 'pagseguro.uol.com.br', logoClearbit: 'https://logo.clearbit.com/pagseguro.uol.com.br', logoBrandfetch: 'https://cdn.brandfetch.io/pagseguro.uol.com.br/w/200/h/200', brandColor: '#00B247', notes: 'Brazil payments & PoS' },
  { id: 139, slug: 'Pix', name: 'Pix', nameLocal: 'Pix', type: 'wallet', subtype: 'bank_transfer', country: 'Brazil', region: 'Latin America', currency: 'BRL', domain: 'bcb.gov.br', logoClearbit: 'https://logo.clearbit.com/bcb.gov.br', logoBrandfetch: 'https://cdn.brandfetch.io/bcb.gov.br/w/200/h/200', brandColor: '#01C4A0', notes: "Brazil's instant payment system" },
  { id: 136, slug: 'MercadoPago', name: 'Mercado Pago', nameLocal: 'Mercado Pago', type: 'wallet', subtype: 'mobile_payment', country: 'Argentina', region: 'Latin America', currency: 'USD', domain: 'mercadopago.com', logoClearbit: 'https://logo.clearbit.com/mercadopago.com', logoBrandfetch: 'https://cdn.brandfetch.io/mercadopago.com/w/200/h/200', brandColor: '#009EE3', notes: "MercadoLibre's fintech; 50M+ users" },
  { id: 128, slug: 'GCash', name: 'GCash', nameLocal: 'GCash', type: 'wallet', subtype: 'mobile_payment', country: 'Philippines', region: 'Southeast Asia', currency: 'PHP', domain: 'gcash.com', logoClearbit: 'https://logo.clearbit.com/gcash.com', logoBrandfetch: 'https://cdn.brandfetch.io/gcash.com/w/200/h/200', brandColor: '#007DFF', notes: 'Philippines #1 e-wallet; 81M users' },
  { id: 129, slug: 'Maya', name: 'Maya', nameLocal: 'Maya', type: 'wallet', subtype: 'neobank', country: 'Philippines', region: 'Southeast Asia', currency: 'PHP', domain: 'maya.ph', logoClearbit: 'https://logo.clearbit.com/maya.ph', logoBrandfetch: 'https://cdn.brandfetch.io/maya.ph/w/200/h/200', brandColor: '#6DC067', notes: 'Digital bank + wallet; formerly PayMaya' },
  { id: 130, slug: 'OVO', name: 'OVO', nameLocal: 'OVO', type: 'wallet', subtype: 'mobile_payment', country: 'Indonesia', region: 'Southeast Asia', currency: 'IDR', domain: 'ovo.id', logoClearbit: 'https://logo.clearbit.com/ovo.id', logoBrandfetch: 'https://cdn.brandfetch.io/ovo.id/w/200/h/200', brandColor: '#4C3494', notes: "Grab's Indonesia wallet; 100M+" },
  { id: 131, slug: 'GoPay', name: 'GoPay', nameLocal: 'GoPay', type: 'wallet', subtype: 'mobile_payment', country: 'Indonesia', region: 'Southeast Asia', currency: 'IDR', domain: 'gopay.co.id', logoClearbit: 'https://logo.clearbit.com/gopay.co.id', logoBrandfetch: 'https://cdn.brandfetch.io/gopay.co.id/w/200/h/200', brandColor: '#00AED6', notes: "Gojek's payment arm" },
  { id: 132, slug: 'DANA', name: 'DANA', nameLocal: 'DANA', type: 'wallet', subtype: 'mobile_payment', country: 'Indonesia', region: 'Southeast Asia', currency: 'IDR', domain: 'dana.id', logoClearbit: 'https://logo.clearbit.com/dana.id', logoBrandfetch: 'https://cdn.brandfetch.io/dana.id/w/200/h/200', brandColor: '#1080D0', notes: 'Ant Group-backed; 140M users' },
  { id: 133, slug: 'TrueMoney', name: 'TrueMoney', nameLocal: 'TrueMoney', type: 'wallet', subtype: 'mobile_payment', country: 'Thailand', region: 'Southeast Asia', currency: 'THB', domain: 'truemoney.com', logoClearbit: 'https://logo.clearbit.com/truemoney.com', logoBrandfetch: 'https://cdn.brandfetch.io/truemoney.com/w/200/h/200', brandColor: '#FF6000', notes: 'Charoen Pokphand Group' },
  { id: 134, slug: 'VNPay', name: 'VNPay', nameLocal: 'VNPay', type: 'wallet', subtype: 'payment_gateway', country: 'Vietnam', region: 'Southeast Asia', currency: 'VND', domain: 'vnpay.vn', logoClearbit: 'https://logo.clearbit.com/vnpay.vn', logoBrandfetch: 'https://cdn.brandfetch.io/vnpay.vn/w/200/h/200', brandColor: '#D81921', notes: "Vietnam's largest payment gateway" },
  { id: 135, slug: 'MoMo', name: 'MoMo', nameLocal: 'MoMo', type: 'wallet', subtype: 'mobile_payment', country: 'Vietnam', region: 'Southeast Asia', currency: 'VND', domain: 'momo.vn', logoClearbit: 'https://logo.clearbit.com/momo.vn', logoBrandfetch: 'https://cdn.brandfetch.io/momo.vn/w/200/h/200', brandColor: '#A50064', notes: "Vietnam's top e-wallet; 31M users" },
  { id: 140, slug: 'MPesa', name: 'M-Pesa', nameLocal: 'M-Pesa', type: 'wallet', subtype: 'mobile_money', country: 'Kenya', region: 'Africa', currency: 'KES', domain: 'safaricom.com', logoClearbit: 'https://logo.clearbit.com/safaricom.com', logoBrandfetch: 'https://cdn.brandfetch.io/safaricom.com/w/200/h/200', brandColor: '#4CAF50', notes: "Africa's most iconic mobile money; 30M+" },
  { id: 142, slug: 'BinancePay', name: 'Binance Pay', nameLocal: '币安支付', type: 'wallet', subtype: 'crypto_payment', country: 'Global', region: 'Global', currency: 'USD', domain: 'binance.com', logoClearbit: 'https://logo.clearbit.com/binance.com', logoBrandfetch: 'https://cdn.brandfetch.io/binance.com/w/200/h/200', brandColor: '#F0B90B', notes: 'Crypto payment by Binance' },
];

const countriesSet = new Set(WALLET_ICONS.map(w => w.country));
const countriesArray = Array.from(countriesSet);
const chinaIndex = countriesArray.indexOf('China');
if (chinaIndex > 0) {
  countriesArray.splice(chinaIndex, 1);
  countriesArray.unshift('China');
}
export const WALLET_ICON_COUNTRIES = countriesArray;

export const WALLET_ICON_REGIONS = [...new Set(WALLET_ICONS.map(w => w.region).filter(Boolean))].sort() as string[];

export function getWalletIconById(id: number): WalletIcon | undefined {
  return WALLET_ICONS.find(w => w.id === id);
}

export function getWalletIconBySlug(slug: string): WalletIcon | undefined {
  return WALLET_ICONS.find(w => w.slug === slug);
}

export function filterWalletIcons(options: {
  type?: 'bank' | 'wallet' | 'all';
  country?: string;
  region?: string;
  search?: string;
}): WalletIcon[] {
  let filtered = WALLET_ICONS;
  
  if (options.type && options.type !== 'all') {
    filtered = filtered.filter(w => w.type === options.type);
  }
  
  if (options.country) {
    filtered = filtered.filter(w => w.country === options.country);
  }

  if (options.region) {
    filtered = filtered.filter(w => w.region === options.region);
  }
  
  if (options.search) {
    const searchLower = options.search.toLowerCase();
    filtered = filtered.filter(w => 
      w.name.toLowerCase().includes(searchLower) ||
      w.slug.toLowerCase().includes(searchLower) ||
      (w.nameLocal && w.nameLocal.includes(options.search!))
    );
  }
  
  return filtered;
}

export function getCountryName(country: string, language: 'zh' | 'en'): string {
  if (language === 'zh') {
    return COUNTRY_NAMES_ZH[country] || country;
  }
  return country;
}
